### ISSUE TITLE
3D Manufacturing Links Require Sign-In

### ISSUE THREAD

**Issue by JustinClough** [SCOREC/Albany#2]
Maybe this was on purpose but the links to the 3D manufacturing sims require the user to sign-in and request permission from the owner.

I think they should be shared to that anyone can view without having to sign-in/request access. 

@RuixiongHu can you look into editing the links to do this or let me know why you'd like to keep them as is?

**Comment by RuixiongHu** [comment]
Thanks for pointing out I've changed the settings for public review
